import type { Metadata } from "next"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import { ptBR } from "@clerk/localizations"
import { Mulish } from "next/font/google"

const mulish = Mulish({
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider
			localization={ptBR}
			appearance={{
				baseTheme: dark,
				signIn: {
					baseTheme: dark,
				},
			}}
		>
			<html lang="en">
				<body className={`${mulish.className} dark antialiased`}>
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
